// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    signIn: '<p class="title">Sign in with your Zooniverse account</p>\n<p class="errors"></p>\n<form>\n  <label><span>Username</span> <input type="text" name="username" required="required" /></label>\n  <label><span>Password</span> <input type="password" name="password" required="required" /></label>\n  <button type="submit">Sign in</button>\n</form>\n<p class="progress">Signing in...</p>',
    signUp: '<p class="title">Sign up for a new Zooniverse account</p>\n<p class="errors"></p>\n<form>\n  <label><span>Username</span> <input type="text" name="username" required="required" /></label>\n  <label><span>Email address</span> <input type="text" name="email" required="required" /></label>\n  <label><span>Password</span> <input type="password" name="password" required="required" /></label>\n  <label><span>Password (confirm)</span> <input type="password" name="password-confirm" required="required" /></label>\n  <label class="privacy-policy"><input type="checkbox" name="policy" required="required" /> I agree to the <a href="https://www.zooniverse.org/privacy" target="_blank">privacy policy</a></label>\n  <button type="submit">Sign up</button>\n</form>\n<p class="progress">Creating account and signing in...</p>',
    reset: '<p>Enter your <strong>username</strong> or <strong>email address</strong> and we\'ll send you instructions on how to reset your password</p>\n<p class="errors"></p>\n<form>\n  <label><input type="text" name="email" required="required" /></label>\n  <button type="submit">Submit</button>\n</form>\n<p class="progress">Check your email for instructions!</p>',
    signOut: '<form>\n  <p>Currently logged in as <strong class="current"></strong>. <button type="submit">Sign out</button></p>\n</form>\n<p class="progress">Signing out...</p>',
    login: '<div class="sign-in"></div>\n<div class="sign-up"></div>\n<div class="reset"></div>\n\n<div class="picker">\n  <button name="sign-in">Already have an account? Sign in!</button>\n  <button name="sign-up">Don\'t have an account? Create one!</button>\n  <!--<button name="reset">Forgot your username or password?</button>-->\n</div>\n\n<div class="sign-out"></div>'
  };

}).call(this);
