// Generated by CoffeeScript 1.3.3
(function() {
  var Form, User;

  Form = require('./controllers/base_form');

  User = require('../models/user');

  describe('SignInForm', function() {
    beforeEach(function() {
      return this.signInForm = new Form.SignInForm;
    });
    describe('#onSubmit', function() {
      beforeEach(function() {
        this.signInForm.usernameField.val('test');
        this.signInForm.passwordField.val('password');
        return this.signInForm.onSubmit();
      });
      it('should show a progress indicator', function() {
        var progress;
        progress = this.signInForm.progress.css('display');
        return expect(progress).not.toBe('none');
      });
      it('forgets any previous errors', function() {
        var errors;
        errors = this.signInForm.errors.text();
        return expect(errors).toBe("");
      });
      return it('submits a username and password to the authentication iframe', function() {
        spyOn(User, 'login').andCallThrough();
        this.signInForm.onSubmit();
        return expect(User.login).toHaveBeenCalledWith({
          username: 'test',
          password: 'password'
        });
      });
    });
    describe('#onErrror', function() {
      beforeEach(function() {
        return this.signInForm.onError("Test Error");
      });
      it('shows an error', function() {
        var errors;
        errors = this.signInForm.errors.text();
        return expect(errors).toBe("Test Error");
      });
      return it('hides the progress indicator', function() {
        var progress;
        progress = this.signInForm.progress.css('display');
        return expect(progress).toBe('none');
      });
    });
    return describe('#onSignIn', function() {
      beforeEach(function() {
        return this.signInForm.onSignIn();
      });
      return it('should hide the progress', function() {
        var progress;
        progress = this.signInForm.progress.css('display');
        return expect(progress).toBe('none');
      });
    });
  });

  describe('SignUpForm', function() {
    beforeEach(function() {
      return this.signUpForm = new Form.SignUpForm;
    });
    return describe('#onSumbit', function() {
      beforeEach(function() {
        this.signUpForm.usernameField.val('test');
        this.signUpForm.passwordField.val('password');
        return this.signUpForm.emailField.val('test@example.com');
      });
      describe('non-matching passwords', function() {
        beforeEach(function() {
          return this.signUpForm.passwordConfirmField.val('lump-password');
        });
        return it('should call #onError with a message', function() {
          spyOn(this.signUpForm, 'onError');
          this.signUpForm.onSubmit();
          return expect(this.signUpForm.onError).toHaveBeenCalledWith('Passwords must match!');
        });
      });
      return describe('matching passwords', function() {
        beforeEach(function() {
          return this.signUpForm.passwordConfirmField.val('password');
        });
        return it('should call User.signup', function() {
          spyOn(User, 'signup').andCallThrough();
          this.signUpForm.onSubmit();
          return expect(User.signup).toHaveBeenCalledWith({
            username: 'test',
            password: 'password',
            email: 'test@example.com'
          });
        });
      });
    });
  });

  describe('SignOutForm', function() {
    beforeEach(function() {
      var userCheck;
      this.signOutForm = new Form.SignOutForm;
      userCheck = false;
      User.login({
        username: 'name',
        password: 'password'
      }).always(function() {
        return userCheck = true;
      });
      return waitsFor(function() {
        return userCheck;
      });
    });
    return describe('#onSubmit', function() {
      return it('should log the user out', function() {
        spyOn(User, 'logout').andCallThrough();
        this.signOutForm.onSubmit();
        return expect(User.logout).toHaveBeenCalled();
      });
    });
  });

}).call(this);
