// Generated by CoffeeScript 1.3.3
(function() {

  describe('LoginForm', function() {
    describe('on submit', function() {
      it('gets a "waiting" class', function() {});
      it('forgets any previous errors', function() {});
      return it('submits a username and password to the authentication iframe', function() {});
    });
    describe('on login error', function() {
      it('gets an "error" class', function() {});
      it('loses its "waiting" class', function() {});
      return it('displays the error', function() {});
    });
    describe('when given a bad username/password combo', function() {
      it('gets an "error" class', function() {});
      it('loses its "waiting" class', function() {});
      return it('displays the error', function() {});
    });
    return describe('on successful login', function() {
      it('updates the logged in username', function() {});
      return it('clears the login form', function() {});
    });
  });

}).call(this);
