// Generated by CoffeeScript 1.3.3
(function() {
  var Api, ProfileItem, Recent, Subject, User;

  Recent = require('./models/recent');

  ProfileItem = require('./models/profile_item');

  User = require('./models/user');

  Api = require('./api');

  Subject = require('./models/subject');

  describe('Recent', function() {
    beforeEach(function() {
      return Api.init();
    });
    it('should be defined', function() {
      return expect(Recent).toBeDefined();
    });
    it('should be instantiable', function() {
      var recent;
      recent = new Recent;
      return expect(recent).not.toBeNull();
    });
    return describe('#fetch', function() {
      return it('should create records from the return JSON', function() {
        var fetchCheck;
        User.current = {
          id: 1
        };
        User.project = 'test';
        fetchCheck = false;
        Recent.fetch().always(function() {
          return fetchCheck = true;
        });
        waitsFor(function() {
          return fetchCheck;
        });
        return runs(function() {
          expect(Recent.first()).not.toBeNull();
          return expect(Recent.first().subjects).toEqual(jasmine.any(Subject));
        });
      });
    });
  });

}).call(this);
