// Generated by CoffeeScript 1.3.3
(function() {
  var Api, Recent, User;

  Recent = require('./models/recent');

  User = require('./models/user');

  Api = require('./api');

  describe('Recent', function() {
    beforeEach(function() {
      return Api.init();
    });
    it('should be defined', function() {
      return expect(Recent).toBeDefined();
    });
    it('should be instantiable', function() {
      var recent;
      recent = new Recent;
      return expect(recent).not.toBeNull();
    });
    return describe('#fetch', function() {
      beforeEach(function() {
        User.project = 'test';
        return User.current = {
          id: '1'
        };
      });
      it('should retrieve recents from the user', function() {
        spyOn(Api, 'get');
        Recent.fetch();
        return expect(Api.get).toHaveBeenCalled();
      });
      return it('should create records from the return JSON', function() {
        var fetchCheck;
        fetchCheck = false;
        Recent.fetch().always(function() {
          return fetchCheck = true;
        });
        waitsFor(function() {
          return fetchCheck;
        });
        return runs(function() {
          console.log(Recent.first());
          expect(Recent.first()).not.toBeNull();
          return expect(Recent.all()).not.toBe([]);
        });
      });
    });
  });

}).call(this);
