// Generated by CoffeeScript 1.3.3
(function() {
  var TopBar;

  TopBar = require('./controllers/top_bar');

  describe('TopBar', function() {
    beforeEach(function() {
      return this.topBar = new TopBar({
        languages: {
          en: 'English',
          fr: 'Français'
        },
        app: "test"
      });
    });
    it('should be instantiable', function() {
      return expect(this.topBar).not.toBeNull();
    });
    return describe('#updateLanguages', function() {
      return it('should add a node for each language in @langauges', function() {
        this.topBar.updateLanguages();
        return expect(this.topBar.languageLabel.text()).toBe("EN");
      });
    });
  });

}).call(this);
