// Generated by CoffeeScript 1.3.3
(function() {
  var TopBar, User;

  TopBar = require('./controllers/top_bar');

  User = require('./models/user');

  describe('TopBar', function() {
    beforeEach(function() {
      return this.topBar = new TopBar({
        languages: {
          en: 'English',
          fr: 'Français'
        },
        app: "test",
        appName: "Test App"
      });
    });
    it('should be instantiable', function() {
      return expect(this.topBar).not.toBeNull();
    });
    describe('#initLanguages', function() {
      return it('should add a node for each language in @langauges', function() {
        this.topBar.initLanguages();
        return expect(this.topBar.langSelect.val()).toBe("en");
      });
    });
    describe('#logIn', function() {
      return it('should call the user login method', function() {
        spyOn(User, 'login');
        this.topBar.el.find('input[name="username"]').val('test');
        this.topBar.el.find('input[name="password"]').val('test');
        this.topBar.logIn();
        return expect(User.login).toHaveBeenCalledWith({
          username: 'test',
          password: 'test'
        });
      });
    });
    return describe('#signIn', function() {
      return it('should activate an alert with signUp form', function() {});
    });
  });

}).call(this);
