// Generated by CoffeeScript 1.3.3
(function() {
  var Api, User;

  User = require('./models/user');

  Api = require('./api');

  describe('User', function() {
    describe('Not logged in', function() {
      return it('should not fetch a user', function() {
        return User.fetch(function(user) {
          return expect(User.current).toBeFalsy();
        });
      });
    });
    return describe('Logged in', function() {
      return it('should fetch a user', function() {
        return Api.getJSON('/login', function() {
          return User.fetch(function(user) {
            return expect(User.current).toBeTruthy();
          });
        });
      });
    });
  });

}).call(this);
