// Generated by CoffeeScript 1.4.0
(function() {
  var $, EventEmitter, ProxyFrame, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = window.zooniverse) == null) {
    window.zooniverse = {};
  }

  EventEmitter = zooniverse.EventEmitter || require('./event-emitter');

  $ = window.jQuery;

  ProxyFrame = (function(_super) {

    __extends(ProxyFrame, _super);

    ProxyFrame.prototype.host = "//" + (+location.port < 1024 ? 'api' : 'dev') + ".zooniverse.org";

    ProxyFrame.prototype.path = '/proxy';

    ProxyFrame.prototype.className = 'proxy-frame';

    ProxyFrame.prototype.ready = false;

    function ProxyFrame(host, path) {
      var _this = this;
      this.host = host != null ? host : this.host;
      this.path = path != null ? path : this.path;
      this.el = $("<iframe src='" + this.host + this.path + "' class='" + this.className + "' style='display: none;'></iframe>");
      this.el.appendTo('body');
      this.el.on('load', function() {
        return _this.onLoad.apply(_this, arguments);
      });
    }

    ProxyFrame.prototype.onLoad = function() {
      this.ready = true;
      return this.trigger('ready');
    };

    return ProxyFrame;

  })(EventEmitter);

  window.zooniverse.ProxyFrame = ProxyFrame;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ProxyFrame;
  }

}).call(this);
