// Generated by CoffeeScript 1.6.3
(function() {
  var ProxyFrame;

  ProxyFrame = window.zooniverse.ProxyFrame;

  describe('ProxyFrame', function() {
    it('creates a new iframe', function() {
      this.proxyFrame = new ProxyFrame({
        host: "" + location.protocol + "//" + location.host,
        path: '/test/helpers/proxy#for-proxy-frame-tests'
      });
      return expect(this.proxyFrame.el.parent()).to.match('body');
    });
    it('queues requests before it\'s ready', function() {
      this.proxyFrame.send({
        url: '/marco'
      });
      this.inQueue = this.proxyFrame.queue[0];
      expect(this.inQueue.url).to.equal('/marco');
      return expect(this.proxyFrame.deferreds[this.inQueue.id]).to.exist;
    });
    it('marks itself ready', function(done) {
      if (this.proxyFrame.ready) {
        return done();
      } else {
        return this.proxyFrame.on('ready', function() {
          return done();
        });
      }
    });
    it('resolves deferreds in the queue when ready', function(done) {
      return this.proxyFrame.deferreds[this.inQueue.id].done(function() {
        return done();
      });
    });
    it('can send a request and receives a response', function(done) {
      return this.proxyFrame.send({
        url: '/marco'
      }, function(response) {
        expect(response).to.equal('polo');
        return done();
      });
    });
    it('removes its iframe when destroyed', function() {
      this.proxyFrame.destroy();
      return expect(this.proxyFrame.el.parent()).not.to.exist;
    });
    return describe('when the back end is unavailable', function() {
      before(function() {
        return this.proxyFrame = new ProxyFrame({
          host: "" + location.protocol + "//" + location.host,
          path: '/doesnt-exist#for-proxy-frame-tests',
          loadTimeout: 100
        });
      });
      after(function() {
        return this.proxyFrame.destroy();
      });
      it('marks itself failed', function(done) {
        if (this.proxyFrame.failed) {
          return done();
        } else {
          return this.proxyFrame.on('fail', function() {
            return done();
          });
        }
      });
      return it('rejects attempted sends', function(done) {
        return this.proxyFrame.send({
          url: '/marco'
        }, null, function() {
          return done();
        });
      });
    });
  });

}).call(this);
