// Generated by CoffeeScript 1.4.0
(function() {
  var Recent, User;

  Recent = window.zooniverse.models.Recent;

  User = window.zooniverse.models.User;

  describe('Recent', function() {
    return it('destroys all instances when the user changes');
  });

}).call(this);
