// Generated by CoffeeScript 1.6.3
(function() {
  var $, $window, Footer, template, _base, _base1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).controllers == null) {
    _base.controllers = {};
  }

  if ((_base1 = window.zooniverse).views == null) {
    _base1.views = {};
  }

  template = window.zooniverse.views.footer || require('../views/footer');

  $ = window.jQuery;

  $window = $(window);

  window.DEFINE_ZOONIVERSE_PROJECT_LIST = function(categories) {
    return $window.trigger('get-zooniverse-project-list', [categories]);
  };

  Footer = (function() {
    Footer.prototype.el = null;

    Footer.prototype.projectScript = 'http://zooniverse-demo.s3-website-us-east-1.amazonaws.com/projects.js';

    function Footer() {
      this.onFetch = __bind(this.onFetch, this);
      this.el = $(document.createElement('div'));
      this.el.addClass('zooniverse-footer');
      this.el.html(template);
      $window.on('get-zooniverse-project-list', this.onFetch);
      this.fetchProjects();
    }

    Footer.prototype.fetchProjects = function() {
      return $.getScript(this.projectScript);
    };

    Footer.prototype.onFetch = function(e, categories) {
      return this.el.html(template({
        categories: categories
      }));
    };

    return Footer;

  })();

  window.zooniverse.controllers.Footer = Footer;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Footer;
  }

}).call(this);
