// Generated by CoffeeScript 1.6.3
(function() {
  var $, Footer, _base, _base1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).controllers == null) {
    _base.controllers = {};
  }

  if ((_base1 = window.zooniverse).views == null) {
    _base1.views = {};
  }

  $ = window.jQuery;

  Footer = (function() {
    Footer.prototype.el = null;

    Footer.prototype.template = window.zooniverse.views.footer || require('../views/footer');

    Footer.prototype.projectJsonUrl = 'http://zooniverse-demo.s3-website-us-east-1.amazonaws.com/projects.json';

    Footer.prototype.sourceLink = 'https://github.com/zooniverse';

    Footer.prototype.privacyLink = 'https://www.zooniverse.org/privacy';

    function Footer(params) {
      this.render = __bind(this.render, this);
      this.fetchProjects = __bind(this.fetchProjects, this);
      var key, value;
      for (key in params) {
        value = params[key];
        this[key] = value;
      }
      this.el = $(document.createElement('div'));
      this.el.addClass('zooniverse-footer');
      this.render();
      this.fetchProjects();
    }

    Footer.prototype.fetchProjects = function() {
      var _this = this;
      return $.getJSON(this.projectJsonUrl, function(categories) {
        _this.categories = categories;
        return _this.render();
      });
    };

    Footer.prototype.render = function() {
      return this.el.html(this.template(this));
    };

    return Footer;

  })();

  window.zooniverse.controllers.Footer = Footer;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Footer;
  }

}).call(this);
