// Generated by CoffeeScript 1.6.3
(function() {
  var $, Controller, Dropdown, GroupsMenu, User, template, _base, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Controller = ((_ref = window.zooniverse) != null ? (_ref1 = _ref.controllers) != null ? _ref1.BaseController : void 0 : void 0) || require('./base-controller');

  User = ((_ref2 = window.zooniverse) != null ? (_ref3 = _ref2.models) != null ? _ref3.User : void 0 : void 0) || require('../models/user');

  template = ((_ref4 = window.zooniverse) != null ? (_ref5 = _ref4.views) != null ? _ref5.groupsMenu : void 0 : void 0) || require('../views/groups-menu');

  $ = window.jQuery;

  Dropdown = ((_ref6 = window.zooniverse) != null ? (_ref7 = _ref6.controllers) != null ? _ref7.Dropdown : void 0 : void 0) || require('./dropdown');

  GroupsMenu = (function(_super) {
    __extends(GroupsMenu, _super);

    GroupsMenu.prototype.className = 'zooniverse-groups-menu';

    GroupsMenu.prototype.events = {
      'click button[name="user-group"]': 'onClickGroupButton'
    };

    function GroupsMenu() {
      this.onUserChangeGroup = __bind(this.onUserChangeGroup, this);
      this.onUserChange = __bind(this.onUserChange, this);
      GroupsMenu.__super__.constructor.apply(this, arguments);
      User.on('change', this.onUserChange);
      User.on('change-group', this.onUserChangeGroup);
    }

    GroupsMenu.prototype.onUserChange = function(e, user) {
      if (user != null) {
        this.el.html(template(user));
        if (user.user_group_id) {
          return this.el.find("button[name='" + user.user_group_id + "']").click();
        }
      }
    };

    GroupsMenu.prototype.onUserChangeGroup = function(e, user, group) {
      var buttons;
      buttons = this.el.find('button[name="user-group"]');
      buttons.removeClass('active');
      if (group != null) {
        return buttons.filter("[value='" + group.id + "']").addClass('active');
      }
    };

    GroupsMenu.prototype.onClickGroupButton = function(e) {
      var target, _ref8;
      target = $(e.currentTarget);
      if ((_ref8 = User.current) != null) {
        _ref8.setGroup(target.val() || 'TODO_HOW_DO_I_STOP_CLASSIFYING_AS_PART_OF_A_GROUP');
      }
      return Dropdown.closeAll();
    };

    return GroupsMenu;

  })(Controller);

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).controllers == null) {
    _base.controllers = {};
  }

  window.zooniverse.controllers.GroupsMenu = GroupsMenu;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = GroupsMenu;
  }

}).call(this);
