// Generated by CoffeeScript 1.3.3
(function() {
  var user;

  user = null;

  $.mockjax({
    url: /^(\/projects\/(\w+))?\/current_user/i,
    response: function(settings) {
      var key, val, _results;
      if (user) {
        this.responseText = {
          success: true
        };
        _results = [];
        for (key in user) {
          val = user[key];
          _results.push(this.responseText[key] = val);
        }
        return _results;
      } else {
        return this.responseText = {
          success: false
        };
      }
    }
  });

  $.mockjax({
    url: /^(\/projects\/(\w+))?\/login/i,
    response: function(settings) {
      var key, val, _results;
      user = {
        id: '4fff22b8c4039a0901000002',
        api_key: '7f4793b00cc97423ca00',
        classification_count: 100,
        name: 'user',
        zooniverse_id: 123456,
        project: {
          classification_count: 10,
          tutorial_done: true
        }
      };
      this.responseText = {
        success: true
      };
      _results = [];
      for (key in user) {
        val = user[key];
        _results.push(this.responseText[key] = val);
      }
      return _results;
    }
  });

  $.mockjax({
    url: /^(\/projects\/(\w+))?\/logout/i,
    response: function(settings) {
      user = null;
      return this.responseText = {
        success: true
      };
    }
  });

  $(window).on('message', function(_arg) {
    var beforeSend, data, dataType, e, headers, id, recipient, request, type, url, _ref,
      _this = this;
    e = _arg.originalEvent;
    recipient = e.origin;
    _ref = JSON.parse(e.data), id = _ref.id, type = _ref.type, url = _ref.url, data = _ref.data, headers = _ref.headers;
    headers || (headers = {});
    dataType = 'json';
    beforeSend = function(xhr) {
      var header, value, _results;
      headers['X-CSRF-Token'] = $('meta[name="csrf-token"]').attr('content');
      _results = [];
      for (header in headers) {
        value = headers[header];
        _results.push(xhr.setRequestHeader(header, value));
      }
      return _results;
    };
    request = $.ajax({
      type: type,
      beforeSend: beforeSend,
      url: url,
      data: data,
      dataType: dataType
    });
    request.done(function(response) {
      return parent.postMessage(JSON.stringify({
        id: id,
        response: response
      }), recipient);
    });
    return request.fail(function(response) {
      return parent.postMessage(JSON.stringify({
        id: id,
        response: response,
        failure: true
      }), recipient);
    });
  });

}).call(this);
