// Generated by CoffeeScript 1.3.3
(function() {
  var user;

  user = null;

  $.mockjax({
    url: /^(\/projects\/(\w+))?\/current_user/i,
    response: function(settings) {
      var key, val, _results;
      if (user) {
        this.responseText = {
          success: true
        };
        _results = [];
        for (key in user) {
          val = user[key];
          _results.push(this.responseText[key] = val);
        }
        return _results;
      } else {
        return this.responseText = {
          success: false
        };
      }
    }
  });

  $.mockjax({
    url: /^(\/projects\/(\w+))?\/login/i,
    response: function(settings) {
      var key, val, _results;
      user = {
        id: '4fff22b8c4039a0901000002',
        api_key: '7f4793b00cc97423ca00',
        classification_count: 100,
        name: 'user',
        zooniverse_id: 123456,
        project: {
          classification_count: 10,
          tutorial_done: true
        }
      };
      this.responseText = {
        success: true
      };
      _results = [];
      for (key in user) {
        val = user[key];
        _results.push(this.responseText[key] = val);
      }
      return _results;
    }
  });

  $.mockjax({
    url: /^(\/projects\/(\w+))?\/logout/i,
    response: function(settings) {
      user = null;
      return this.responseText = {
        success: true
      };
    }
  });

  $.mockjax({
    url: /^\/projects\/\w+\/subjects\?limit=2/i,
    responseText: [
      {
        id: "4fff2d0fc4039a09f10003e0",
        activated_at: "2012-07-27T18:17:19Z",
        coords: [],
        created_at: "2012-07-12T20:01:19Z",
        location: {
          standard: "http://www.seafloorexplorer.org/subjects/standard/ASP0000001.jpg",
          thumbnail: "http://www.seafloorexplorer.org/subjects/thumbnail/ASP0000001.jpg"
        },
        metadata: {},
        project_id: "4fdf8fb3c32dab6c95000001",
        random: 0.3841740452034256,
        state: "active",
        updated_at: "2012-07-27T18:16:46Z",
        workflow_ids: ["4fdf8fb3c32dab6c95000002"],
        zooniverse_id: "ASP0000001"
      }, {
        id: "4fff2c76b0fdc5091c00025c",
        activated_at: "2012-07-12T20:04:38Z",
        classification_count: 3,
        coords: [42.1058, -67.223337],
        created_at: "2012-07-12T19:58:46Z",
        location: {
          standard: "http://www.seafloorexplorer.org/subjects/standard/ASP0000002.jpg",
          thumbnail: "http://www.seafloorexplorer.org/subjects/thumbnail/ASP0000002.jpg"
        },
        metadata: {},
        project_id: "4fdf8fb3c32dab6c95000001",
        random: 0.6838078086002668,
        state: "active",
        updated_at: "2012-07-12T19:58:46Z",
        workflow_ids: ["4fdf8fb3c32dab6c95000002"],
        zooniverse_id: "ASP0000002"
      }
    ]
  });

  $(window).on('message', function(_arg) {
    var beforeSend, data, dataType, e, headers, id, recipient, request, type, url, _ref,
      _this = this;
    e = _arg.originalEvent;
    recipient = e.origin;
    _ref = JSON.parse(e.data), id = _ref.id, type = _ref.type, url = _ref.url, data = _ref.data, headers = _ref.headers;
    headers || (headers = {});
    dataType = 'json';
    beforeSend = function(xhr) {
      var header, value, _results;
      headers['X-CSRF-Token'] = $('meta[name="csrf-token"]').attr('content');
      _results = [];
      for (header in headers) {
        value = headers[header];
        _results.push(xhr.setRequestHeader(header, value));
      }
      return _results;
    };
    request = $.ajax({
      type: type,
      beforeSend: beforeSend,
      url: url,
      data: data,
      dataType: dataType
    });
    request.done(function(response) {
      return parent.postMessage(JSON.stringify({
        id: id,
        response: response
      }), recipient);
    });
    return request.fail(function(response) {
      return parent.postMessage(JSON.stringify({
        id: id,
        response: response,
        failure: true
      }), recipient);
    });
  });

}).call(this);
