// Generated by CoffeeScript 1.6.3
(function() {
  var offset, _base;

  offset = function(el, from) {
    var currentElement, left, top;
    left = 0;
    top = 0;
    currentElement = el;
    while (currentElement != null) {
      if (!isNaN(currentElement.offsetLeft)) {
        left += currentElement.offsetLeft;
      }
      if (!isNaN(currentElement.offsetTop)) {
        top += currentElement.offsetTop;
      }
      currentElement = currentElement.offsetParent;
    }
    left += parseFloat(getComputedStyle(document.body.parentNode).marginLeft);
    top += parseFloat(getComputedStyle(document.body.parentNode).marginTop);
    return {
      left: left,
      top: top
    };
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).util == null) {
    _base.util = {};
  }

  window.zooniverse.util.offset = offset;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = offset;
  }

}).call(this);
