// Generated by CoffeeScript 1.4.0
(function() {
  var offset;

  offset = function(el, from) {
    var currentElement, left, top;
    left = 0;
    top = 0;
    currentElement = el;
    while (currentElement != null) {
      if (!isNaN(currentElement.offsetLeft)) {
        left += currentElement.offsetLeft;
      }
      if (!isNaN(currentElement.offsetTop)) {
        top += currentElement.offsetTop;
      }
      currentElement = currentElement.offsetParent;
    }
    left += parseFloat(getComputedStyle(document.body.parentNode).marginLeft);
    top += parseFloat(getComputedStyle(document.body.parentNode).marginTop);
    return {
      left: left,
      top: top
    };
  };

  module.exports = offset;

}).call(this);
