// Generated by CoffeeScript 1.6.3
(function() {
  var toggleClass, _base,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  toggleClass = function(element, className, condition) {
    var classList, contained;
    classList = element.className.split(/\s+/);
    contained = __indexOf.call(classList, className) >= 0;
    if (condition == null) {
      condition = !contained;
    }
    condition = !!condition;
    if (!contained && condition === true) {
      classList.push(className);
    }
    if (contained && condition === false) {
      classList.splice(classList.indexOf(className), 1);
    }
    element.className = classList.join(' ');
    return null;
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).util == null) {
    _base.util = {};
  }

  window.zooniverse.util.toggleClass = toggleClass;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = toggleClass;
  }

}).call(this);
