// Generated by CoffeeScript 1.3.3
(function() {
  var Favorite, ProfileItem, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ProfileItem = require('./profile_item');

  User = require('./user');

  Favorite = (function(_super) {

    __extends(Favorite, _super);

    Favorite.configure("Favorite", "project_id", "workflow_id", "subjects");

    function Favorite() {
      Favorite.__super__.constructor.apply(this, arguments);
    }

    Favorite.url = function() {
      return "/projects/" + User.project + "/users/" + User.current.id + "/favorites";
    };

    Favorite.fromJSON = function(results) {
      var item, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        item = results[_i];
        _results.push(item = Favorite.create(item));
      }
      return _results;
    };

    return Favorite;

  })(ProfileItem);

  module.exports = Favorite;

}).call(this);
