// Generated by CoffeeScript 1.3.3
(function() {
  var $, Api, Group, Model, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('./model');

  Api = require('../api');

  $ = require('jqueryify');

  _ = require('underscore/underscore');

  Group = (function(_super) {

    __extends(Group, _super);

    function Group() {
      return Group.__super__.constructor.apply(this, arguments);
    }

    Group.configure('Group');

    Group.prototype.projectName = null;

    Group.prototype.type = null;

    Group.url = function(params) {
      return this.withParams("/projects/" + this.prototype.projectName + "/groups", params);
    };

    Group.index = function(opts) {
      var _this = this;
      if (opts == null) {
        opts = {};
      }
      opts = _({
        page: 1,
        per_page: 5
      }).extend(opts);
      return Api.get(this.url(opts), function(results) {
        var result, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          _results.push(_this.create(result));
        }
        return _results;
      });
    };

    Group.show = function(id) {
      var _this = this;
      return Api.get("" + (this.url()) + "/" + id, function(result) {
        return _this.create(result);
      });
    };

    return Group;

  })(Model);

  module.exports = Group;

}).call(this);
