// Generated by CoffeeScript 1.3.3
(function() {
  var Api, Model, ProfileItem, Subject, User, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Api = require('../api');

  Model = require('./model');

  User = require('./user');

  Subject = require('./subject');

  _ = require('underscore/underscore');

  ProfileItem = (function(_super) {

    __extends(ProfileItem, _super);

    ProfileItem.configure("ProfileItem", "project_id", "workflow_id", "subjects", "created_at");

    function ProfileItem() {
      ProfileItem.__super__.constructor.apply(this, arguments);
      if (this.subjects) {
        this.convertSubjects();
      }
      if (this.created_at) {
        this.convertDates();
      }
    }

    ProfileItem.prototype.convertSubjects = function() {
      if (this.subjects[0]) {
        return this.subjects = new Subject(this.subjects[0]);
      }
    };

    ProfileItem.prototype.convertDates = function() {
      if (this.created_at) {
        return this.created_at = new Date(this.created_at);
      }
    };

    ProfileItem.fetch = function(opts) {
      var fetcher;
      if (opts == null) {
        opts = {};
      }
      opts = _({
        page: 1,
        per_page: 10
      }).extend(opts);
      fetcher = Api.get(this.url(opts), this.fromJSON);
      ProfileItem.__super__.constructor.fetch.apply(this, arguments);
      return fetcher;
    };

    return ProfileItem;

  })(Model);

  module.exports = ProfileItem;

}).call(this);
