// Generated by CoffeeScript 1.3.3
(function() {
  var Api, Model, ProfileItem, Subject, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Api = require('../api');

  Model = require('./model');

  User = require('./user');

  Subject = require('./subject');

  ProfileItem = (function(_super) {

    __extends(ProfileItem, _super);

    ProfileItem.configure("ProfileItem", "project_id", "workflow_id", "subjects");

    function ProfileItem() {
      ProfileItem.__super__.constructor.apply(this, arguments);
      if (this.subjects) {
        this.convertSubjects();
      }
    }

    ProfileItem.prototype.convertSubjects = function() {
      return this.subjects = new Subject(this.subjects[0]);
    };

    ProfileItem.fetch = function() {
      var fetcher, url;
      url = this.url();
      fetcher = Api.get(url, this.fromJSON);
      return fetcher;
    };

    return ProfileItem;

  })(Model);

  module.exports = ProfileItem;

}).call(this);
