// Generated by CoffeeScript 1.3.3
(function() {
  var ProfileItem, Recent, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ProfileItem = require('./profile_item');

  User = require('./user');

  Recent = (function(_super) {

    __extends(Recent, _super);

    Recent.configure("Recent", "project_id", "workflow_id", "subjects");

    function Recent() {
      Recent.__super__.constructor.apply(this, arguments);
    }

    Recent.url = function() {
      return "/projects/" + User.project + "/users/" + User.current.id + "/recents";
    };

    Recent.fromJSON = function(results) {
      var item, _i, _len, _results;
      console.log("Results: ", results);
      _results = [];
      for (_i = 0, _len = results.length; _i < _len; _i++) {
        item = results[_i];
        _results.push(Recent.create(item));
      }
      return _results;
    };

    return Recent;

  })(ProfileItem);

  module.exports = Recent;

}).call(this);
