// Generated by CoffeeScript 1.3.3
(function() {
  var $, Api, Model, Subject, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('./model');

  Api = require('../api');

  $ = require('jqueryify');

  _ = require('underscore/underscore');

  Subject = (function(_super) {

    __extends(Subject, _super);

    function Subject() {
      return Subject.__super__.constructor.apply(this, arguments);
    }

    Subject.configure('Subject', 'zooniverse_id', 'coords', 'location', 'metadata');

    Subject.prototype.projectName = null;

    Subject.url = function(params) {
      return this.withParams("/projects/" + this.prototype.projectName + "/subjects", params);
    };

    Subject.fetch = function(count) {
      var fetcher,
        _this = this;
      if (count == null) {
        count = 1;
      }
      return fetcher = Api.get(this.url({
        limit: count
      }), function(results) {
        var result, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = results.length; _i < _len; _i++) {
          result = results[_i];
          _results.push(_this.create(result));
        }
        return _results;
      });
    };

    return Subject;

  })(Model);

  module.exports = Subject;

}).call(this);
