// Generated by CoffeeScript 1.3.3
(function() {
  var Api, Model, ProxyFrame, User,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Model = require('./model');

  Api = require('../api');

  ProxyFrame = require('../proxy_frame');

  User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.configure('User');

    User.fetch = function() {
      var fetcher,
        _this = this;
      fetcher = Api.getJSON('/current_user', function(result) {
        return User.current = result.success ? (delete result.success, new User(result)) : null;
      });
      fetcher.always(this.setAuthHeaders);
      return fetcher;
    };

    User.setAuthHeaders = function() {
      var auth;
      if (User.current) {
        auth = base64.encode("" + User.current.name + ":" + User.current.apiKey);
        return ProxyFrame.headers['Authorization'] = "Basic " + auth;
      } else {
        return delete ProxyFrame.headers['Authorization'];
      }
    };

    return User;

  })(Model);

  module.exports = User;

}).call(this);
