// Generated by CoffeeScript 1.3.3
(function() {
  var $, anchors, className, root, updateClasses;

  $ = require('jqueryify');

  className = 'active';

  root = document;

  anchors = $();

  updateClasses = function() {
    anchors.removeClass(className);
    anchors = $("a[href^='" + location.hash + "']");
    return anchors.addClass(className);
  };

  module.exports = {
    init: function(newClassName, newRoot) {
      var _ref;
      if (newClassName == null) {
        newClassName = className;
      }
      if (newRoot == null) {
        newRoot = root;
      }
      _ref = [newClassName, newRoot], className = _ref[0], root = _ref[1];
      updateClasses();
      return $(window).on('hashchange', updateClasses);
    }
  };

}).call(this);
