// Generated by CoffeeScript 1.4.0
(function() {
  var $, Api, EventEmitter, ProxyFrame, id, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  if ((_ref = window.zooniverse) == null) {
    window.zooniverse = {};
  }

  EventEmitter = window.zooniverse.EventEmitter || require('../lib/event-emitter');

  ProxyFrame = window.zooniverse.ProxyFrame || require('./proxy-frame');

  $ = window.jQuery;

  id = -1;

  Api = (function(_super) {

    __extends(Api, _super);

    Api.current = null;

    Api.prototype.project = '.';

    Api.prototype.headers = {};

    Api.prototype.proxyFrame = null;

    function Api(_arg) {
      var host, loadTimeout, path, _ref1;
      _ref1 = _arg != null ? _arg : {}, this.project = _ref1.project, host = _ref1.host, path = _ref1.path, loadTimeout = _ref1.loadTimeout;
      this.proxyFrame = new ProxyFrame({
        host: host,
        path: path,
        loadTimeout: loadTimeout
      });
      this.select();
    }

    Api.prototype.request = function(type, url, data, done, fail) {
      var _ref1;
      if (typeof data === 'function') {
        _ref1 = [done, data, null], fail = _ref1[0], done = _ref1[1], data = _ref1[2];
        this.trigger('request', [type, url, data]);
      }
      return this.proxyFrame.send({
        type: type,
        url: url,
        data: data,
        headers: this.headers
      }, done, fail);
    };

    Api.prototype.get = function() {
      return window.req = this.request.apply(this, ['get'].concat(__slice.call(arguments)));
    };

    Api.prototype.getJSON = function() {
      return this.request.apply(this, ['getJSON'].concat(__slice.call(arguments)));
    };

    Api.prototype.post = function() {
      return this.request.apply(this, ['post'].concat(__slice.call(arguments)));
    };

    Api.prototype.put = function() {
      return this.request.apply(this, ['put'].concat(__slice.call(arguments)));
    };

    Api.prototype["delete"] = function() {
      return this.request.apply(this, ['delete'].concat(__slice.call(arguments)));
    };

    Api.prototype.select = function() {
      this.trigger('select');
      return this.constructor.current = this;
    };

    return Api;

  })(EventEmitter);

  window.zooniverse.Api = Api;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Api;
  }

}).call(this);
