// Generated by CoffeeScript 1.3.3
(function() {
  var $, Api, ProxyFrame, _,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice;

  $ = require('jqueryify');

  _ = require('underscore/underscore');

  ProxyFrame = require('proxy_frame');

  Api = (function() {

    Api.requests = {};

    Api.ready = false;

    Api.proxy = void 0;

    function Api(host) {
      this.host = host;
      this.process = __bind(this.process, this);

      this.respond = __bind(this.respond, this);

      this.loaded = __bind(this.loaded, this);

      this["delete"] = __bind(this["delete"], this);

      this.put = __bind(this.put, this);

      this.post = __bind(this.post, this);

      this.getJSON = __bind(this.getJSON, this);

      this.get = __bind(this.get, this);

      this.host || (this.host = "" + window.location.protocol + "//" + window.location.host);
      if (!Api.proxy) {
        this.createProxy();
      }
    }

    Api.prototype.get = function() {
      return this.request.apply(this, ['get'].concat(__slice.call(arguments)));
    };

    Api.prototype.getJSON = function() {
      return this.request.apply(this, ['getJSON'].concat(__slice.call(arguments)));
    };

    Api.prototype.post = function() {
      return this.request.apply(this, ['post'].concat(__slice.call(arguments)));
    };

    Api.prototype.put = function() {
      return this.request.apply(this, ['put'].concat(__slice.call(arguments)));
    };

    Api.prototype["delete"] = function() {
      return this.request.apply(this, ['delete'].concat(__slice.call(arguments)));
    };

    Api.prototype.createProxy = function() {
      Api.proxy = new ProxyFrame(this.host);
      Api.proxy.bind('load', this.loaded);
      return Api.proxy.bind('response', this.respond);
    };

    Api.prototype.loaded = function() {
      var id, request, _ref, _results;
      Api.ready = true;
      _ref = Api.requests;
      _results = [];
      for (id in _ref) {
        request = _ref[id];
        if (!request.processed) {
          _results.push(this.process(id));
        }
      }
      return _results;
    };

    Api.prototype.request = function(type, url, data, done, fail) {
      var id, message;
      id = this.nextId();
      if (typeof data === 'function') {
        fail = done;
        done = data;
        data = null;
      }
      message = {
        id: id,
        type: type,
        url: url,
        data: data,
        done: done,
        fail: fail
      };
      Api.requests[id] = message;
      if (Api.ready) {
        return this.process(id);
      } else {
        return message.processed = false;
      }
    };

    Api.prototype.respond = function(ev, message) {
      var request;
      request = Api.requests[message.id];
      if (message.failure) {
        if (typeof request.fail === "function") {
          request.fail(message.response);
        }
      } else {
        if (typeof request.done === "function") {
          request.done(message.response);
        }
      }
      return delete Api.requests[message.id];
    };

    Api.prototype.process = function(id) {
      var message;
      Api.requests[id].processed = true;
      message = _(Api.requests[id]).pick('id', 'type', 'url', 'data', 'headers');
      return Api.proxy.send(message);
    };

    Api.prototype.nextId = function() {
      return _.uniqueId('api-');
    };

    return Api;

  })();

  module.exports = Api;

}).call(this);
