// Generated by CoffeeScript 1.3.3
(function() {
  var $, Dialog;

  $ = require('jqueryify');

  Dialog = require('./dialog');

  module.exports = {
    init: function() {
      return $(document).on('click', '[data-popup]', function(e) {
        var arrowDirection, attachment, className, contentNode, popup, position, target, _ref;
        target = $(e.currentTarget);
        _ref = target.attr('data-popup').split(/\s+/), contentNode = _ref[0], position = _ref[1], className = _ref[2];
        contentNode = $(contentNode);
        switch (position) {
          case 'top':
            attachment = {
              y: 'bottom',
              to: target,
              at: {
                y: 'top'
              }
            };
            arrowDirection = 'bottom';
            break;
          case 'right':
            attachment = {
              x: 'left',
              to: target,
              at: {
                x: 'right'
              }
            };
            arrowDirection = 'left';
            break;
          case 'bottom':
            attachment = {
              y: 'top',
              to: target,
              at: {
                y: 'bottom'
              }
            };
            arrowDirection = 'top';
            break;
          case 'left':
            attachment = {
              x: 'right',
              to: target,
              at: {
                x: 'left'
              }
            };
            arrowDirection = 'right';
        }
        popup = new Dialog({
          className: 'popup',
          title: contentNode.attr('title'),
          content: contentNode.html(),
          attachment: attachment,
          arrowDirection: arrowDirection,
          buttons: [],
          callback: function() {
            return popup.destroy();
          }
        });
        if (className != null) {
          popup.el.addClass(className);
        }
        return popup.open();
      });
    }
  };

}).call(this);
