// Generated by CoffeeScript 1.3.3
(function() {
  var $, BarGraph,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty;

  $ = require('jqueryify');

  BarGraph = (function() {

    BarGraph.prototype.x = null;

    BarGraph.prototype.y = null;

    BarGraph.prototype.floor = 0;

    BarGraph.prototype.ceiling = NaN;

    BarGraph.prototype.valueStyle = 'height';

    BarGraph.prototype.el = null;

    BarGraph.prototype.className = 'bar-chart';

    BarGraph.prototype.items = null;

    function BarGraph(params) {
      this.render = __bind(this.render, this);

      var property, value, _ref;
      for (property in params) {
        if (!__hasProp.call(params, property)) continue;
        value = params[property];
        this[property] = value;
      }
      if ((_ref = this.el) == null) {
        this.el = $("<div class='" + this.constructor.prototype.className + "'></div>");
      }
      this.el = $(this.el);
      this.el.addClass(this.className);
      this.render();
    }

    BarGraph.prototype.render = function() {
      var i, label, max, xAxisLabel, xLabels, yAxisLabel, yValues, _i, _len, _ref, _ref1, _results;
      this.el.empty();
      _ref = this.y;
      for (yAxisLabel in _ref) {
        yValues = _ref[yAxisLabel];
        max = this.ceiling || Math.ceil(Math.max.apply(Math, yValues));
        this.el.append("<div class=\"y axis\">\n  <div class=\"label\">" + yAxisLabel + "</div>\n  <!--TODO: Y-axis Marks-->\n</div>");
      }
      _ref1 = this.x;
      _results = [];
      for (xAxisLabel in _ref1) {
        xLabels = _ref1[xAxisLabel];
        for (i = _i = 0, _len = xLabels.length; _i < _len; i = ++_i) {
          label = xLabels[i];
          this.el.append("<div class=\"item\" data-index=\"" + i + "\" data-value=\"" + yValues[i] + "\">\n  <div class=\"bar\" style=\"" + this.valueStyle + ": " + (100 * ((yValues[i] - this.floor) / (max - this.floor))) + "%;\"></div>\n  <div class=\"label\">" + yValues[i] + " " + yAxisLabel + "</div>\n</div>");
        }
        this.items = this.el.find('.item');
        _results.push(this.el.append("<div class=\"x axis\">\n  <div class=\"label\">" + xAxisLabel + "</div>\n  <!--TODO: Y-axis Marks-->\n</div>"));
      }
      return _results;
    };

    return BarGraph;

  })();

  module.exports = BarGraph;

}).call(this);
