// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    topBar: {
      username: 'Username',
      password: 'Password',
      signIn: 'Sign in',
      signOut: 'Sign out',
      forgotPassword: 'Forgot your password?',
      noAccount: 'Don\'t have an account?',
      signUp: 'Sign up',
      welcome: 'Welcome',
      messages: 'messages'
    },
    user: {
      badLogin: 'Incorrect username or password',
      signInFailed: 'Sign in failed.'
    }
  };

}).call(this);
