// Generated by CoffeeScript 1.3.3
(function() {
  var $, googleAnalyticsSrc, init, track,
    _this = this;

  $ = require('jqueryify');

  googleAnalyticsSrc = 'http://www.google-analytics.com/ga.js';

  if (window.location.protocol === 'https:') {
    googleAnalyticsSrc = googleAnalyticsSrc.replace('http://www', 'https://ssl');
  }

  init = function(_arg, trackHashes) {
    var account, domain, _ref;
    account = _arg.account, domain = _arg.domain;
    if (trackHashes == null) {
      trackHashes = true;
    }
    if ((_ref = window._gaq) == null) {
      window._gaq = [];
    }
    window._gaq.push(['_setAccount', account]);
    if (domain) {
      window._gaq.push(['_setDomainName', domain]);
    }
    window._gaq.push(['_trackPageview']);
    if (trackHashes) {
      $(window).on('hashchange', track);
    }
    return $.getScript(googleAnalyticsSrc);
  };

  track = function(location) {
    if (typeof location !== 'string') {
      location = null;
    }
    return window._gaq.push(['_trackPageview', location || window.location.href]);
  };

  module.exports = {
    init: init,
    track: track
  };

}).call(this);
