// Generated by CoffeeScript 1.3.3
(function() {
  var $, getSrc, googleAnalyticsSrc, init, queue, track,
    _this = this;

  $ = require('jqueryify');

  googleAnalyticsSrc = 'http://www.google-analytics.com/ga.js';

  if (window.location.protocol === 'https:') {
    googleAnalyticsSrc = googleAnalyticsSrc.replace('http://www', 'https://ssl');
  }

  getSrc = null;

  queue = null;

  init = function(_arg, noHashChange) {
    var account, domain;
    account = _arg.account, domain = _arg.domain;
    if (noHashChange == null) {
      noHashChange = false;
    }
    return getSrc = $.getScript(googleAnalyticsSrc, function() {
      var _ref,
        _this = this;
      queue = (_ref = window._gaq) != null ? _ref : window._gaq = [['_setAccount', account], ['_setDomainName', domain], ['_trackPageview']];
      if (!noHashChange) {
        $(window).on('hashchange', function() {
          return track(window.location.href);
        });
      }
      return getSrc;
    });
  };

  track = function(location) {
    return getSrc.done(function() {
      return queue.push(['_trackPageview', location || window.location]);
    });
  };

  module.exports = {
    init: init,
    track: track
  };

}).call(this);
