// Generated by CoffeeScript 1.4.0
(function() {
  var $, EventEmitter, ProxyFrame, messageId, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = window.zooniverse) == null) {
    window.zooniverse = {};
  }

  EventEmitter = zooniverse.EventEmitter || require('./event-emitter');

  $ = window.jQuery;

  messageId = -1;

  ProxyFrame = (function(_super) {

    __extends(ProxyFrame, _super);

    ProxyFrame.REJECTION = 'ProxyFrame not connected';

    ProxyFrame.prototype.host = "//" + (+location.port < 1024 ? 'api' : 'dev') + ".zooniverse.org";

    ProxyFrame.prototype.path = '/proxy';

    ProxyFrame.prototype.loadTimeout = 5000;

    ProxyFrame.prototype.className = 'proxy-frame';

    ProxyFrame.prototype.ready = false;

    ProxyFrame.prototype.failed = false;

    ProxyFrame.prototype.deferreds = null;

    ProxyFrame.prototype.queue = null;

    function ProxyFrame(params) {
      var property, value, _ref1, _ref2,
        _this = this;
      if (params == null) {
        params = {};
      }
      for (property in params) {
        if (!__hasProp.call(params, property)) continue;
        value = params[property];
        if (property in this) {
          this[property] = value;
        }
      }
      if ((_ref1 = this.deferreds) == null) {
        this.deferreds = [];
      }
      if ((_ref2 = this.queue) == null) {
        this.queue = [];
      }
      this.el = $("<iframe src='" + this.host + this.path + "' class='" + this.className + "' style='display: none;'></iframe>");
      this.el.appendTo('body');
      this.el.on('load', function() {
        return _this.onLoad.apply(_this, arguments);
      });
      setTimeout((function() {
        if (!_this.ready) {
          return _this.onFailed();
        }
      }), this.loadTimeout);
      $(window).on('message', function(_arg) {
        var e;
        e = _arg.originalEvent;
        if (e.source === _this.el.get(0).contentWindow) {
          return _this.onMessage.apply(_this, arguments);
        }
      });
    }

    ProxyFrame.prototype.onLoad = function() {
      var payload, _i, _len, _ref1, _results,
        _this = this;
      if (this.failed) {
        return;
      }
      if (!!~this.el.get(0).contentDocument.title.toUpperCase().indexOf('PROXY')) {
        this.ready = true;
        this.trigger('ready');
        return setTimeout((function() {
          var payload, _i, _len, _ref1, _results;
          _ref1 = _this.queue;
          _results = [];
          for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
            payload = _ref1[_i];
            _results.push(_this.process(payload));
          }
          return _results;
        }), 100);
      } else {
        this.onFailed();
        _ref1 = this.queue;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          payload = _ref1[_i];
          _results.push(this.deferreds[payload.id].reject(this.constructor.REJECTION));
        }
        return _results;
      }
    };

    ProxyFrame.prototype.onFailed = function() {
      this.failed = true;
      return this.trigger('failed');
    };

    ProxyFrame.prototype.send = function(payload, done, fail) {
      var deferred;
      messageId += 1;
      payload.id = messageId;
      deferred = new $.Deferred;
      deferred.then(done, fail);
      this.deferreds[messageId] = deferred;
      if (this.failed) {
        deferred.reject(this.constructor.REJECTION);
      } else if (this.ready) {
        this.process(payload);
      } else {
        this.queue.push(payload);
      }
      return deferred.promise();
    };

    ProxyFrame.prototype.process = function(payload) {
      return this.el.get(0).contentWindow.postMessage(JSON.stringify(payload), this.host);
    };

    ProxyFrame.prototype.onMessage = function(_arg) {
      var e, message;
      e = _arg.originalEvent;
      message = JSON.parse(e.data);
      if (message.failure) {
        this.deferreds[message.id].reject(message.response);
      } else {
        this.deferreds[message.id].resolve(message.response);
      }
      return this.trigger('response', [message]);
    };

    return ProxyFrame;

  })(EventEmitter);

  window.zooniverse.ProxyFrame = ProxyFrame;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ProxyFrame;
  }

}).call(this);
