// Generated by CoffeeScript 1.3.3
(function() {
  var Api, ProxyFrame, User;

  Api = require('./api');

  ProxyFrame = require('./proxy_frame');

  User = {
    current: null,
    fetch: function(callback) {
      var _this = this;
      return Api.getJSON('/current_user', function(result) {
        _this.current = result.success ? (delete result.success, result) : null;
        _this.setAuthHeaders();
        return typeof callback === "function" ? callback(_this.current) : void 0;
      });
    },
    setAuthHeaders: function() {
      var auth;
      if (this.current) {
        auth = base64.encode("" + this.current.name + ":" + this.current.apiKey);
        return ProxyFrame.headers['Authorization'] = "Basic " + auth;
      } else {
        return delete ProxyFrame.headers['Authorization'];
      }
    }
  };

  module.exports = User;

}).call(this);
