// Generated by CoffeeScript 1.3.3
(function() {
  var Zooniverse;

  Zooniverse = {
    Api: require('api'),
    ProxyFrame: require('proxy_frame'),
    User: require('user')
  };

  module.exports = Zooniverse;

}).call(this);
