// Generated by CoffeeScript 1.3.3
(function() {
  var $, BrowserCheck,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty;

  $ = require('jqueryify');

  BrowserCheck = (function() {

    BrowserCheck.prototype.view = '<div class="zooniverse-browser-warning">\n  <section>\n    <div class="summary">\n      <p>This site probably won\'t work until you update your browser.</p>\n    </div>\n\n    <div class="recommend">\n      <p>We recommend using <a href="http://www.mozilla.org/firefox/" target="_blank">Mozilla Firefox</a> or <a href="http://www.google.com/chrome" target="_blank">Google Chrome</a>.</p>\n    </div>\n\n    <div class="ie">\n      <p>If you use <a href="http://www.microsoft.com/windows/internet-explorer/" target="_blank">Microsoft Internet Explorer</a>, make sure you\'re running the latest version.</p>\n      <p>If you can\'t install the latest Internet Explorer, try <a href="http://google.com/chromeframe" target="_blank">Chrome Frame</a>!</p>\n    </div>\n\n    <div class="action">\n      <p><button name="dismiss">Dismiss</button></p>\n    </div>\n  </section>\n</div>';

    BrowserCheck.prototype.support = {
      mozilla: 14,
      msie: 8,
      webkit: 530,
      opera: Infinity
    };

    function BrowserCheck(params) {
      var property, value, _ref;
      if (params == null) {
        params = {};
      }
      this.dismiss = __bind(this.dismiss, this);

      for (property in params) {
        if (!__hasProp.call(params, property)) continue;
        value = params[property];
        this[property] = value;
      }
      if ((_ref = this.el) == null) {
        this.el = $(this.view);
      }
      this.el.on('click', 'button[name="dismiss"]', this.dismiss);
    }

    BrowserCheck.prototype.check = function() {
      if (!this.supported()) {
        return this.warn();
      }
    };

    BrowserCheck.prototype.supported = function() {
      var supportedVersion, vendor, version;
      version = parseFloat($.browser.version);
      for (vendor in $.browser) {
        if (vendor in this.support) {
          supportedVersion = this.support[vendor];
        }
      }
      return version >= supportedVersion;
    };

    BrowserCheck.prototype.warn = function() {
      return this.el.appendTo('body');
    };

    BrowserCheck.prototype.dismiss = function() {
      return this.el.remove();
    };

    return BrowserCheck;

  })();

  module.exports = BrowserCheck;

}).call(this);
