// Generated by CoffeeScript 1.3.3
(function() {
  var $, BaseForm, Controller, User, templates,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $ = require('jqueryify');

  User = require('../models/user');

  Controller = require('./controller');

  templates = require('../views/login_form');

  BaseForm = (function(_super) {

    __extends(BaseForm, _super);

    BaseForm.prototype.events = {
      sumbit: 'onSubmit',
      keydown: 'onInputChange',
      change: 'onInputChange'
    };

    BaseForm.prototype.elements = {
      '.errors': 'errors',
      'input[name="username"]': 'usernameField',
      'input[name="email"]': 'emailField',
      'input[name="password"]': 'passwordField',
      'input[name="password-confirm"]': 'passwordCOnfirmField',
      'input[name="policy"]': 'submitButton',
      'button[type="submit"]': 'submitButton',
      '.progress': 'progress',
      'input[required]': 'requiredInputs'
    };

    function BaseForm() {
      BaseForm.__super__.constructor.apply(this, arguments);
      this.html(this.template);
    }

    return BaseForm;

  })(Controller);

  module.exports = {};

}).call(this);
