// Generated by CoffeeScript 1.3.3
(function() {
  var Controller, Dialog, Form, LoginForm, TopBar, User,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  User = require('../models/user');

  Controller = require('./controller');

  Form = require('./base_form');

  Dialog = require('../dialog');

  LoginForm = require('zooniverse/lib/controllers/login_form');

  TopBar = (function(_super) {

    __extends(TopBar, _super);

    TopBar.prototype.className = 'zooniverse-top-bar';

    TopBar.prototype.events = {
      'click button[name="login"]': 'logIn',
      'click button[name="signup"]': 'onClickSignUp',
      'click button[name="signout"]': 'signOut',
      'keypress input': 'logInOnEnter',
      'click a.top-bar-button': 'toggleDisplay',
      'change select.language': 'setLanguage'
    };

    function TopBar() {
      this.onClickSignUp = __bind(this.onClickSignUp, this);

      this.logInOnEnter = __bind(this.logInOnEnter, this);

      this.setLanguage = __bind(this.setLanguage, this);

      this.initLanguages = __bind(this.initLanguages, this);

      this.onError = __bind(this.onError, this);

      this.setUser = __bind(this.setUser, this);

      this.render = __bind(this.render, this);

      this.toggleDisplay = __bind(this.toggleDisplay, this);

      this.startSignUp = __bind(this.startSignUp, this);

      this.signOut = __bind(this.signOut, this);

      this.logIn = __bind(this.logIn, this);

      var _this = this;
      TopBar.__super__.constructor.apply(this, arguments);
      this.app || (this.app = "test");
      this.appName || (this.appName = "Test Name");
      this.currentLanguage || (this.currentLanguage = 'en');
      User.project = this.app;
      User.bind('sign-in', this.setUser);
      User.bind('sign-in-error', this.onError);
      User.fetch().always(function() {
        if (!User.current) {
          return _this.toggleDisplay();
        }
      });
      this.render();
      this.setAppName();
      this.initLanguages();
      this.setUser();
      this.loginForm = new LoginForm;
      this.loginDialog = new Dialog({
        content: this.loginForm.el,
        buttons: [
          {
            'Close': null
          }
        ]
      });
      this.loginDialog.dialog.addClass('login');
    }

    TopBar.prototype.elements = {
      '#zooniverse-top-bar-container': 'container',
      '#app-name': 'appNameContainer',
      '#zooniverse-top-bar-login .login': 'loginContainer',
      '#zooniverse-top-bar-login .welcome': 'welcomeContainer',
      'select.language': 'langSelect',
      '.login .progress': 'progress',
      '.login .errors': 'errors'
    };

    TopBar.prototype.logIn = function(e) {
      var login, password, username;
      username = this.el.find('input[name="username"]').val();
      password = this.el.find('input[name="password"]').val();
      if ((username !== '') && (password !== '')) {
        this.el.find('.progress').show();
        return login = User.login({
          username: username,
          password: password
        });
      }
    };

    TopBar.prototype.signOut = function(e) {
      return User.logout();
    };

    TopBar.prototype.startSignUp = function(e) {
      var d, form;
      form = new Form.SignUpForm;
      d = new Dialog({
        content: form.el.html(),
        buttons: [],
        attachment: {
          to: '.dialog-underlay'
        }
      });
      d.el.find('.dialog').addClass('sign-up');
      d.open();
      return console.log(d);
    };

    TopBar.prototype.toggleDisplay = function(e) {
      if (e != null) {
        if (typeof e.preventDefault === "function") {
          e.preventDefault();
        }
      }
      return this.el.parent().toggleClass('show-top-bar');
    };

    TopBar.prototype.render = function() {
      return this.html(require('../views/top_bar'));
    };

    TopBar.prototype.setAppName = function() {
      return this.appNameContainer.append(this.appName);
    };

    TopBar.prototype.setUser = function() {
      var _ref;
      if (User.current) {
        if ((_ref = this.signUp) != null) {
          _ref.el.remove();
        }
        this.loginContainer.hide();
        this.errors.empty();
        this.welcomeContainer.html(this.userGreeting(User.current.name));
        this.welcomeContainer.show();
        if (this.el.parent().hasClass('show-top-bar')) {
          return setTimeout(this.toggleDisplay, 1000);
        }
      } else {
        this.welcomeContainer.hide();
        this.loginContainer.show();
        return this.progress.hide();
      }
    };

    TopBar.prototype.userGreeting = function(user) {
      return "<div class=\"inputs\">\n  <h3> Hi, <strong>" + user + "</strong>. Welcome to " + this.appName + "!</h3>\n</div>\n<div class=\"buttons\">\n  <button name=\"signout\" type=\"button\">Sign Out</button>\n</div>";
    };

    TopBar.prototype.onError = function(error) {
      this.progress.hide();
      this.errors.text(error);
      return this.errors.show();
    };

    TopBar.prototype.initLanguages = function() {
      var longLang, shortLang, _ref;
      _ref = this.languages;
      for (shortLang in _ref) {
        longLang = _ref[shortLang];
        this.langSelect.append("<option value=\"" + shortLang + "\">" + (shortLang.toUpperCase()) + "</option>");
      }
      return this.langSelect.val('en');
    };

    TopBar.prototype.setLanguage = function(e) {
      this.currentLanguage = this.langSelect.val();
      return this.el.trigger('request-translation', this.currentLanguage);
    };

    TopBar.prototype.logInOnEnter = function(e) {
      if (e.keyCode === 13) {
        return this.logIn();
      }
    };

    TopBar.prototype.onClickSignUp = function() {
      this.loginDialog.open();
      return this.loginForm.signUpButton.click();
    };

    return TopBar;

  })(Controller);

  module.exports = TopBar;

}).call(this);
