// Generated by CoffeeScript 1.6.3
(function() {
  var cs, _base;

  cs = {
    topBarHeading: 'Zooniverse projekt'
    signUpHeading: 'Vytvoření Zooniverse účtu',
    signInHeading: 'Přihlašování na Zooniverse účet',
    signUp: 'Zaregistrovat se'
    signIn: 'Přihlásit se'
    signOut: 'Odhlásit se'
    username: 'Uživatelské jméno'
    password: 'Heslo'
    email: 'Email'
    realName: 'Pravé jméno'
    whyRealName: 'Toto jméno bývá použito při děkování přispěvatelům, např. v rozhovorech nebo na posterech. Pokud si nepřejete, aby bylo Vaše jméno zveřejněno, nechte políčko prázdné.'
    noAccount: 'Nemáte ještě účet?',
    agreeToPrivacyPolicy: 'Souhlasím se <a href="https://www.zooniverse.org/privacy" target="_blank">zásadami ochrany osobních údajů</a>.'
    betaPreference: 'Chci dostávat oznámení o možnosti testování dosud nezveřejněných Zooniverse projektů a poskytování zpětné vazby.'
    forgotPassword: 'Zapomněli jste heslo?'
    badLogin: 'Zadali jste chybné uživatelské jméno, nebo heslo.'
    signInFailed: 'Přihlášení se nezdařilo.'
    signInForProfile: 'K zobrazení Vašeho profilu je nutné se přihlásit.'
    footerHeading: 'Zooniverse je soubor občansko naučných webových projektů, které využívají úsilí dobrovolníků pomoct vědcům zpracovat kvanta dat, jimiž jsou při svém výzkumu zaplaveni.'
    privacyPolicy: 'Zásady ochrany osobních údajů'
    forkOnGitHub: 'Zdrojové soubory & chyby'
    recents: 'Nedávné'
    favorites: 'Oblíbené'
    none: 'Žádné'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.cs = cs;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = cs;
  }

}).call(this);
