// Generated by CoffeeScript 1.6.3
(function() {
  var el, _base;

  el = {
    topBarHeading: 'Ενα προγραμμα του Zooniverse',
    signUpHeading: 'Εγγραφειτε για ενα νεο λογαριασμο στο Zooniverse',
    signInHeading: 'Συνδεθειτε στο λογαριασμο Zooniverse σας',
    signUp: 'Εγγραφη',
    signIn: 'Συνδεση',
    signOut: 'Αποσυνδεση',
    username: 'Ονομα χρηστη',
    password: 'Κωδικος',
    email: 'Email',
    realName: 'Πραγματικο ονομα',
    whyRealName: 'Αυτο θα χρησιμοποιηθει οταν ευχαριστησουμε τους συνεργατες, για παραδειγμα,σε συζητησεις ή σε αφισες.Εαν δεν θελετε να αναφερθειτε δημοσια, αφηστε το κενο.',
    noAccount: 'Δεν εχετε λογαριασμο;',
    agreeToPrivacyPolicy: 'Συμφωνω με την <a href="https://www.zooniverse.org/privacy" target="_blank">πολιτικη απορρητου</a>.',
    betaPreference: 'Επιθυμω να λαμβανω ειδοποιησεις με ευκαιριες να δοκιμασω και να κανω σχολια σε ακυκλοφορητα προγραμματα του Zooniverse.',
    forgotPassword: 'Ξεχάσατε τον κωδικό σας;',
    badLogin: 'Λαθος ονομα χρηστη ή κωδικος.',
    signInFailed: 'Η συνδεση απετυχε.',
    signInForProfile: 'Συνδεθειτε για να δειτε το προφιλ σας.',
    footerHeading: 'Το Zooniverse είναι μια συλλογη επιστημονικων προγραμματων μεσω ιντερνετ που βασιζονται στη συνεισφορα εθελοντων ωστε να βοηθησουν τους ερευνητες να διαχειριστουν τον τεραστιο ογκο δεδομενων που εχουν διαθεσιμο.',
    privacyPolicy: 'Πολιτικη απορρητου',
    forkOnGitHub: 'Κωδικας &amp; σφαλματα',
    recents: 'Προσφατα',
    favorites: 'Αγαπημενα',
    none: 'Κανενα'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.el = el;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = el;
  }

}).call(this);
