// Generated by CoffeeScript 1.6.3
(function() {
  var en, _base;

  en = {
    topBarHeading: 'A Zooniverse project',
    signUpHeading: 'Sign up for a new Zooniverse account',
    signInHeading: 'Sign in to your Zooniverse account',
    signUp: 'Sign up',
    signIn: 'Sign in',
    signOut: 'Sign out',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    realName: 'Real name',
    whyRealName: 'This will be used when we thank contributors, for example, in talks or on posters.<br />If you don\'t want to be mentioned publicly, leave this blank.',
    noAccount: 'Don\'t have an account?',
    privacyPolicy: 'I agree to the <a href="https://www.zooniverse.org/privacy" target="_blank">privacy policy</a>.',
    forgotPassword: 'Forgot your password?',
    badLogin: 'Incorrect username or password',
    signInFailed: 'Sign in failed.',
    signInForProfile: 'Sign in to see your profile.',
    footerHeading: 'The Zooniverse is a collection of web-based citizen science projects that use the efforts of volunteers to help researchers deal with the flood of data that confronts them.',
    privacyPolicy: 'Privacy policy',
    recents: 'Recents',
    favorites: 'Favorites',
    none: 'none'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.en = en;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = en;
  }

}).call(this);
