// Generated by CoffeeScript 1.6.3
(function() {
  var en, _base;

  en = {
    topBarHeading: 'A Zooniverse project',
    signUp: 'Sign up',
    signIn: 'Sign in',
    signOut: 'Sign out',
    footerHeading: 'The Zooniverse is a collection of web-based citizen science projects that use the efforts of volunteers to help researchers deal with the flood of data that confronts them.'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.en = en;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = en;
  }

}).call(this);
