// Generated by CoffeeScript 1.6.3
(function() {
  var it, _base;

  it = {
    topBarHeading: 'Un progetto Zooniverse',
    signUpHeading: 'Crea un profilo Zooniverse',
    signInHeading: 'Accedi a Zooniverse',
    signUp: 'Registrati',
    signIn: 'Accedi',
    signOut: 'Esci',
    username: 'Nome utente',
    password: 'Password',
    email: 'Email',
    realName: 'Nome reale',
    whyRealName: 'Questo dato serve per ringraziare e citare i volontari: ad esempio, in presentazioni e poster. Se non vuoi che il tuo nome venga utilizzato in pubblico, lascia questo spazio vuoto.',
    noAccount: 'Non hai un profilo?',
    agreeToPrivacyPolicy: 'Accetto le <a href="https://www.zooniverse.org/privacy" target="_blank">Politiche sulla privacy</a>.',
    betaPreference: 'Vorrei ricevere notifiche per poter testare e commentare i progetti Zooniverse non ancora pubblicati.',
    forgotPassword: 'Hai dimenticato la password?',
    badLogin: 'Nome utente o password errati',
    signInFailed: 'Si è verificato un errore durante la registrazione',
    signInForProfile: 'Accedi al profilo.',
    footerHeading: 'Zooniverse è una raccolta di progetti di scienza dei cittadini basati sulla collaborazione di volontari che aiutano i ricercatori nel gestire dei flussi di dati.',
    privacyPolicy: 'Privacy',
    forkOnGitHub: 'Sorgenti & bug',
    recents: 'Recenti',
    favorites: 'Preferiti',
    none: 'nessuno'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.it = it;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = it;
  }

}).call(this);
