// Generated by CoffeeScript 1.6.3
(function() {
  var it, _base;

  it = {
    topBarHeading: 'Un progetto Zooniverse',
    signUpHeading: 'Crea un profilo Zooniverse',
    signInHeading: 'Accedi al tuo profilo Zooniverse',
    signUp: 'Registrati',
    signIn: 'Entra',
    signOut: 'Esci',
    username: 'Username',
    password: 'Password',
    email: 'Email',
    realName: 'Nome reale',
    whyRealName: 'Questo verra\' utilizzato per ringraziare i collaboratori, ad esempio, in presentazioni e posters. Se non vuoi che il tuo nome venga utilizzato in pubblico, lascia questo spazio vuoto.', 
    noAccount: 'Non hai un profilo?',
    agreeToPrivacyPolicy: 'Accetto <a href="https://www.zooniverse.org/privacy" target="_blank">le norme sulla Privacy</a>.',
    betaPreference: 'Vorrei ricevere notifiche per testare e commentare su progetti Zooniverse non ancora pubblicati.',
    forgotPassword: 'Hai dimenticato la tua password?',
    badLogin: 'Username or password incorretti',
    signInFailed: 'Sign in failed.',
    signInForProfile: 'Accedi al tuo profilo.',
    footerHeading: 'Zooniverse è una raccolta di progetti web di Citizen Science basati sull\'utilizzo di volontari che aiutano i ricercatori nel gestire flussi di dati.',
    privacyPolicy: 'Privacy',
    forkOnGitHub: 'Codice & errori',
    recents: 'Recenti',
    favorites: 'Favoriti',
    none: 'Non presente'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.it = it;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = it;
  }

}).call(this);