// Generated by CoffeeScript 1.6.3
(function() {
  var ja, _base;

  ja = {
    topBarHeading: 'ズーニバース・プロジェクト',
    signUpHeading: 'ズーニバース・アカウントの新規登録を行う',
    signInHeading: 'あなたのズーニバース・アカウントへログインする',
    signUp: 'アカウント登録',
    signIn: 'ログイン',
    signOut: 'ログアウト',
    username: 'ユーザー名',
    password: 'パスワード',
    email: 'Eメール',
    realName: '本名',
    whyRealName: '本名は研究発表の謝辞などに掲載させていただくことがあります。ご希望でない方は空欄のままでお願いしま す。',
    noAccount: 'アカウントをお持ちでない方へ',
    agreeToPrivacyPolicy: '<a href="https://www.zooniverse.org/privacy" target="_blank">プライバシー規約に同意する</a>.',
    betaPreference: '新しいズーニバース・プロジェクトの試験に参加したい。',
    forgotPassword: 'パスワードを忘れた場合',
    badLogin: 'ユーザー名またはパスワードが間違っています。',
    signInFailed: 'ログインできませんでした。',
    signInForProfile: 'プロフィール確認',
    footerHeading: 'Tズーニバースは、一般の方々がインターネットで簡単に参加できる科学研究プロジェクトの集まりです。それぞれのプロジェクトが、一般の方々にもわかりやすいデータを大量にかかえており、みなさまにその整理 を手伝っていただいてます。',
    privacyPolicy: 'プライバシー規約',
    forkOnGitHub: 'ソースコードおよびバグ',
    recents: '最新情報',
    favorites: 'お気に入り',
    none: '選択なし'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.ja = ja;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ja;
  }

}).call(this);
