// Generated by CoffeeScript 1.6.3
(function() {
  var ru, _base;

  ru = {
    topBarHeading: 'Проект Zooniverse',
    signUpHeading: 'Создать новый аккаунт Zooniverse',
    signInHeading: 'Войти в ваш аккаунт Zooniverse',
    signUp: 'Зарегистрироваться',
    signIn: 'Войти',
    signOut: 'Выйти',
    username: 'Имя пользователя',
    password: 'Пароль',
    email: 'Адрес E-mail',
    realName: 'Настоящее имя',
    whyRealName: 'Используется при выражении нашей благодарности участникам, например, в обсуждениях или объявлениях. Если вы не хотите, чтобы вас упоминали публично, оставьте это поле пустым.',
    noAccount: 'Нет аккаунта?',
    agreeToPrivacyPolicy: 'Я согласен с <a href="https://www.zooniverse.org/privacy" target="_blank">политикой конфиденциальности</a>.',
    betaPreference: 'Я хочу получать приглашения к участию в тестировании новых проектов Zooniverse.',
    forgotPassword: 'Забыли пароль?',
    badLogin: 'Неправильное имя пользователя или пароль',
    signInFailed: 'Вход не выполнен.',
    signInForProfile: 'Войдите, чтобы увидеть свой профиль.',
    footerHeading: 'Zooniverse — это группа онлайн-проектов гражданской науки, где добровольцы помогают обрабатывать огромные объемы данных, с которыми приходится сталкиваться учёным.',
    privacyPolicy: 'Политика конфиденциальности',
    forkOnGitHub: 'Исходный код и баги',
    recents: 'Недавние',
    favorites: 'Избранное',
    none: 'пусто'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.ru = ru;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = ru;
  }

}).call(this);
