// Generated by CoffeeScript 1.6.3
(function() {
  var zh_cn, _base;

  zh_cn = {
    topBarHeading: 'Zooniverse计划',
    signUpHeading: ' "申请新的Zooniverse帐号',
    signInHeading: '登入Zooniverse',
    signUp: '申请帐号',
    signIn: '登入',
    signOut: '登出',
    username: '用户名',
    password: '密码',
    email: '电子信箱帐号',
    realName: '真实姓名',
    whyRealName: '将会被用来感谢我们的协力伙伴，譬如放在演讲场合或海报上。如果你不愿公开真实姓名，可以空白。 ',
    noAccount: '还没开立过帐号吗？ ',
    agreeToPrivacyPolicy: '我同意<a href="https://www.zooniverse.org/privacy" target="_blank">隐私权设定规定</a>.',
    betaPreference: '我愿意帮忙测试尚未正式上线的 "Zooniverse计划" 并协助让程式更完善，有这类机会请通知我。 ',
    forgotPassword: '忘记密码?',
    badLogin: '用户名称错误或密码错误',
    signInFailed: '登入失败。 ',
    signInForProfile: '登入查看已分类记录。 ',
    footerHeading: ' Zooniverse网站以网路方式让一般大众能参与多种研究主题的科学计划。海量的资料原本給科学家带来不小的挑战，还好有志愿者分类员协同努力，已帮助科学家处理了大量资料。 ',
    privacyPolicy: '隐私权设定规定',
    forkOnGitHub: '原始码及错误回报',
    recents: '最新完成的',
    favorites: '我的最爱',
    none: '无'
  };

  if (window.zooniverse == null) {
    window.zooniverse = {};
  }

  if ((_base = window.zooniverse).translations == null) {
    _base.translations = {};
  }

  window.zooniverse.translations.zh_cn = zh_cn;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = zh_cn;
  }

}).call(this);
