// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, User, api, _base, _ref, _ref1,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if ((_ref = window.zooniverse) == null) {
    window.zooniverse = {};
  }

  if ((_ref1 = (_base = window.zooniverse).models) == null) {
    _base.models = {};
  }

  EventEmitter = zooniverse.EventEmitter || require('../lib/event-emitter');

  api = zooniverse.api || require('../lib/api');

  User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.fetch = function() {
      var fetcher,
        _this = this;
      fetcher = api.getJSON("/projects/" + api.project + "/current_user", this.createUser);
      fetcher.always(this.setAuthHeaders);
      fetcher.always(function() {
        return User.trigger('sign-in');
      });
      return fetcher;
    };

    return User;

  })(EventEmitter);

  window.zooniverse.models.User = User;

  if (typeof module !== "undefined" && module !== null) {
    module.exports = User;
  }

}).call(this);
